config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :categories
    resources :users
  end

  resources :users
  resources :ideas


  get      '/login', to: 'sessions#new'
  post     '/login', to: 'sessions#create'
  delete  '/logout', to: 'sessions#destroy'

  root 'sessions#new'
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :ideas

  validates :name, presence: true, uniqueness: true
end

app/models/idea.rb
class Idea < ActiveRecord::Base
  belongs_to :user
  belongs_to :category

  validates :title, :description, :user_id, :category_id, presence: true

  def owned_by?(current_user_id)
    user_id == current_user_id
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :ideas, dependent: :destroy

  validates :name, presence: true
  validates :username, presence: true, uniqueness: true

  has_secure_password

  enum role: %w(default admin)

  def to_param
    username
  end

  def admin?
    role == "admin"
  end

end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController

  # def verify_is_admin
  #   (current_user.nil?) ? redirect_to(root_path) : (redirect_to(root_path) unless current_user.admin?)
  # end

end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::BaseController

  before_filter :current_admin?

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def show
    @category = Category.find(params[:id])
  end

  def edit
    @category = Category.find(params[:id])
  end

  def create
    category = Category.new(name: category_params[:name])

    if category.save 
      redirect_to admin_categories_path(category)
    else
      flash[:errors] = category.errors.full_messages.join(', ')
      render :edit
    end
  end

  def update
    @category = Category.find(params[:id])

    if @category.update(category_params)
      redirect_to admin_categories_path(@category)
    else
      flash[:errors] = @category.errors.full_messages.join(', ')
      render :edit
    end
  end

  def destroy
    @category = Category.find(params[:id])
    if @category.ideas.size == 0
      @category.destroy
    else
      flash[:errors] = "This category is already assigned to ideas, cannot delete."
    end
    redirect_to admin_categories_path
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController

  before_filter :current_admin?

  def show
    @user = User.find_by(username: params[:id])
  end

  def index
    @users = User.all
  end

  def edit
    @user = User.find_by(username: params[:id])
  end 

  def update
    user = User.find_by(username: user_params[:username])

    if user.update(role: user_params[:role])
      flash[:notice] = "#{params[:user][:username]} is now a #{params[:user][:role]} user."
      redirect_to admin_user_path(user)
    else
      flash[:errors] = user.errors.full_messages.join(', ')
      render :edit
    end
  end

  def destroy
    @user = User.find_by(username: params["id"]).destroy
    flash[:notice] = "User has been deleted"
    redirect_to admin_users_path
  end

  private

  def user_params 
    params.require(:user).permit(:username, :role, :id)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def current_admin?
    redirect_to root_path unless current_user && current_user.admin?
  end

  def user_owns_idea?(idea)
    idea.owned_by?(current_user.id)
  end

  # def not_found
  #   raise ActionController::RoutingError.new('Not Found')
  # end

end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController

  before_filter :current_user

  def show
    idea = Idea.find_by(id: params[:id])
    
    if idea && user_owns_idea?(idea)
      @idea = idea
    else
      redirect_to user_path(current_user)
    end
  end

  def edit
    idea = Idea.find_by(id: params[:id])

    if idea && user_owns_idea?(idea)
      @idea = idea
    else
      flash[:errors] = idea.errors.full_messages.join(', ')
      render :edit
    end
  end

  def update
    idea = current_user.find_by(id: idea_params[:id])

    if idea && user_owns_idea?(idea)
      @idea = idea.update(idea_params)
      redirect_to idea_path(@idea) 
    else
      flash[:errors] 
      redirect_to user_path(current_user)
    end
  end 

  def create
    idea = Idea.new(title: idea_params[:title], 
                    description: idea_params[:description], 
                    user_id: current_user.id,
                    category_id: idea_params[:category_id])

    if current_user && idea.save
      redirect_to idea_path(idea)
    else
      flash[:errors] = idea.errors.full_messages.join(', ')
      redirect_to new_idea_path
    end
  end

  def destroy
    idea = Idea.find(params[:id])
    idea.destroy if user_owns_idea?(idea)
    redirect_to user_path(current_user)
  end

  private

  def idea_params
    params.require(:idea).permit(:id, :title, :description, :category_id)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  before_filter :current_user

  def new
  end

  def create
    user = User.find_by(username: user_params[:username])

    if user && user.authenticate(user_params[:password])
      session[:user_id] = user.id
      redirect_to user_path(user)
    else
      flash[:error] = "Invalid login."
      render :new
    end
  end

  def destroy
    session.clear
    flash[:notice] = "Logout successful"
    redirect_to login_path
  end

  private

  def user_params 
    params.require(:session).permit(:username, :password)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :current_user

  def show
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/categories/_form.html.erb
<%= form_for(:admin_category, url: :admin_category) do |f| %>
  <%= f.text_area :name, placeholder: "name" %>
  <%= f.submit %>
<% end %>

app/views/admin/categories/edit.html.erb
<%= form_for(@category, url: :admin_category, method: :put) do |f| %>
  <%= f.text_field :name  %>
  <%= f.submit %>
<% end %>

app/views/admin/categories/index.html.erb
<% @categories.each do |category| %>
  <p>
    <%= category.name %>
    <%= link_to "show", admin_category_path(category) %>
    <%= link_to "edit", edit_admin_category_path(category) %>
    <%= button_to "delete", admin_category_path(category), method: :delete %>
  </p>
<% end %>

<%= link_to "Add Category", new_admin_category_path %>

app/views/admin/categories/new.html.erb
<%= form_for(:category, url: :admin_categories) do |f| %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/admin/categories/show.html.erb
<%= @category.name %>
<%= link_to "<< back to categories", admin_categories_path %>

app/views/admin/users/edit.html.erb
<h1> <%= @user.username %> </h1>

<%= form_for(:user, url: :admin_user, method: :put) do |f| %>
  <%= f.text_field :username, :readonly => true %> <br>
  <%= f.radio_button :role, "admin", checked: @user.role == "admin" %> Admin <br>
  <%= f.radio_button :role, "default", checked: @user.role == "default" %> Default <br>
  <%= f.submit "Update" %>
<% end %>

app/views/admin/users/index.html.erb
<h1>Welcome <%= current_user.name %> </h1>

<% @users.each do |user| %>
  <h3><%= user.username %></h3>
  <ul class="nav nav-pills", id="<%=dom_id(user)%>">
    <li><%= link_to "Show", admin_user_path(user), method: :get, class: "btn btn-info", id: "btn-sm"%></li>
    <li><%= link_to "Edit", edit_admin_user_path(user), method: :get, class: "btn btn-info", id: "btn-sm" %></li>
    <li><%= button_to "Delete", admin_user_path(user), method: :delete, class: "btn btn-danger", id: "btn-sm", data: {confirm: "Really?"} %></li>
  </ul>
<% end %>

app/views/admin/users/show.html.erb
<h3>User: <%= @user.username %></h3>

<p>Name: <%= @user.name %></p>
<p>Role: <%= @user.role %></p>

<%= link_to "<< back to users", admin_users_path %>

app/views/ideas/_form.html.erb
<%= form_for(:idea, url: :ideas) do |f| %>
  <%= f.text_field :title, placeholder: "title" %>
  <%= f.text_area :description, placeholder: "description" %>
  <%= f.collection_select(:category_id, Category.all, :id, :name ) %>
  <%= f.submit %>
<% end %>

app/views/ideas/edit.html.erb
<%= render partial: 'form' %>

app/views/ideas/new.html.erb
<%= render partial: 'form' %>

app/views/ideas/show.html.erb
<p><%= @idea.title %></p>
<p><%= @idea.description %></p>
<p><%= Category.find(@idea.category_id).name %></p>

<%= link_to "<< back to ideas", user_path(current_user) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Literail</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% flash.each do |type, message| %>
  <%= content_tag :div, message, id: "flash_#{type}" %>
<% end %>

<% if current_user %>
  <%= button_to "Logout", logout_path, method: :delete %>
<% end %>

<div class="container-fluid">
<%= yield %>
</div>
</body>
</html>

app/views/users/show.html.erb
<h2>Welcome <%= current_user.name %></h2>
<% if current_user.role == "admin" %>
  <p><%= link_to "View Categories", admin_categories_path %></p>
  <p><%= link_to "View Users", admin_users_path %></p>
<% end %>

<% current_user.ideas.each do |idea| %>
  <p>
    <%= link_to idea.title, idea_path(idea) %>
    <%= link_to "edit", edit_idea_path(idea) %>
    <%= button_to "delete", idea_path(idea), method: :delete %>
  </p>
<% end %>

<%= button_to "New Idea", new_idea_path, method: :get %>